#common for client and server
---
parser: '@typescript-eslint/parser'
plugins:
  - '@typescript-eslint'
settings:
  react:
    version: detect
extends:
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier/@typescript-eslint'
  - 'plugin:prettier/recommended'
rules:
  'react/prop-types': off
  'react/display-name': off
  'react/react-in-jsx-scope': off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/camelcase': off
  '@typescript-eslint/no-empty-function': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-use-before-define': off
  '@typescript-eslint/ban-ts-ignore': off
  '@typescript-eslint/ban-ts-comment': off
